---
- name: Configure Web Servers (Web Server 3 and 4)
  hosts: configure_Yes
  become: yes
  tasks:
    - name: Install Apache HTTP Server
      yum:
        name: httpd
        state: present

    - name: Start and Enable Apache Service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Update index.html with project info
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head>
              <title>Ansible Playbooks</title>
            </head>
            <body>
              <h1>Welcome to Web Server 3 and 4</h1>
              <p>Team Members: Ishan Aakash Patel</p>
              <p>Student ID : 146151238</p>
              <p>Project: ACS730 Final Project</p>
              <img src="https://image-final-project-acs.s3.us-east-1.amazonaws.com/1.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAREHDSGVGW2UPQBUA%2F20250412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250412T184943Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGMaCXVzLWVhc3QtMSJGMEQCIHuHEiBU2RZQmIq4RjPcVVZ%2F%2FvEGJsFLr5XPl1Pe4jagAiBQqZQjbqbRVZU%2FVxQVRs25hQ5xKmVqtvfIMq%2BWQlmZMSq%2FBAjc%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAAaDDA3Nzc4NjY1ODEyNSIM7dT1wZOr%2B2HrqErcKpMEwwE0n2AAYMju45%2FP%2Bfz3oZjpyvEvg8w3BUNkBdBI2iVGAsY0spgaNq4iiz3lR71oGRXvRqD3%2FwFUiXf%2BvCAdFUJLA2w6xVQXOtxX3KyB7w55B8QmimEz%2B%2BTX6AwsY8KWy7dInGSaJkj5lV82v%2F7jgpnQhmn7u4Ec2sYRGC%2FwZ6Yx8AUbqOvVpBFtAjjjcRiQLQxq%2Bb7Dtrn7tuNHsUBoa08q2pHVzhGU8v8ea0nwsugOtiKspZbZRg68mX3IpeiWvEhSpK6h3L81hXalUQ0iK2Yfwv4VYO3l3nbN7mc54ykGm88KVy20%2Fd0YHbgnz90fh3J5En18%2Fc3gXmuYOQHgz7TOE1PKoZMsrk9Dn5LH0fOhXQE4zMdJmEKhQKrQeZbRFa7J6OfTTcFrXPN5ZupCLKlAUdw5MSwaqZmBldQLZpJRUvRXYc2f8ilfz%2FCjjBzl5kjJ4SNbn9QUdaePA2Q5zVQefONBAuzrAjGoYwEE1bi2EwOKlrQX5Km015PDGYPczwCr47UhcA%2FhNHSLS91iFBSwvCNVMNDp8Q%2BAGqbYzzoX82qso6gFuPxLKlcWIk8SwQDtbouBcv5LOm4r0MFEZVIHOJdmC7SaK%2BBhDq1fxaZzlw%2B9ukQGzHTkTAL1lA0BC6BF7IbnpGHlSXlw497wbnioGnJbct0S%2Bun3fQbv5UmlPnIpJQgJKvIp6yGus0Xv3FSaMLjW6r8GOqECpLr2z9F%2B9fHbpBqAVXT%2BNAiSEAwDQIHHCtMNnSR1c5Ik6k%2FPiDhj6VUPoZRe5y1vF4NDFo5fjdXML8A%2FnYZVIP6ZKLRX2RGgIRwie2VtHmttoXF%2B%2Bztw8epOt1AWqQEovjceBvQ%2FdQzOwSilSaU9TJSy3iYDVTGQewWsFOLGbZn6fY9bqRnVpugVVOVaJGkYeYrVvzyNKerL0XPvEBudq8arcDd8W7H9m%2B%2BZJYRQQbdRsVXPXKVFmcUCiBkeLoYvJbOq79UvGq%2FsyzNotpfxDmoXNunYIfpLol37JjmkrrK%2BXsK4W7OU9%2BgDlRAppb%2BO5nINpTH6bb3lYTt2qiQatt3sDDLGHi7GLjJC%2FbDyASPastycQx7nH1CKSB54oOTyWA%3D%3D&X-Amz-Signature=c228eb5b1f10fa4bfd14e6c107565f3ed7cf9eaebc8497886d7bbbabe667a8b6" alt="Website Image" style="max-width:100%;height:auto;">
            </body>
          </html>
